// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: join_channel.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "join_channel.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace IM {

namespace {

const ::google::protobuf::Descriptor* JoinChannel_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  JoinChannel_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_join_5fchannel_2eproto() {
  protobuf_AddDesc_join_5fchannel_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "join_channel.proto");
  GOOGLE_CHECK(file != NULL);
  JoinChannel_descriptor_ = file->message_type(0);
  static const int JoinChannel_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JoinChannel, user_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JoinChannel, channel_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JoinChannel, result_),
  };
  JoinChannel_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      JoinChannel_descriptor_,
      JoinChannel::default_instance_,
      JoinChannel_offsets_,
      -1,
      -1,
      -1,
      sizeof(JoinChannel),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JoinChannel, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JoinChannel, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_join_5fchannel_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      JoinChannel_descriptor_, &JoinChannel::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_join_5fchannel_2eproto() {
  delete JoinChannel::default_instance_;
  delete JoinChannel_reflection_;
}

void protobuf_AddDesc_join_5fchannel_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022join_channel.proto\022\002IM\"B\n\013JoinChannel\022"
    "\017\n\007user_id\030\001 \001(\003\022\022\n\nchannel_id\030\002 \001(\005\022\016\n\006"
    "result\030\003 \001(\005b\006proto3", 100);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "join_channel.proto", &protobuf_RegisterTypes);
  JoinChannel::default_instance_ = new JoinChannel();
  JoinChannel::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_join_5fchannel_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_join_5fchannel_2eproto {
  StaticDescriptorInitializer_join_5fchannel_2eproto() {
    protobuf_AddDesc_join_5fchannel_2eproto();
  }
} static_descriptor_initializer_join_5fchannel_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int JoinChannel::kUserIdFieldNumber;
const int JoinChannel::kChannelIdFieldNumber;
const int JoinChannel::kResultFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

JoinChannel::JoinChannel()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:IM.JoinChannel)
}

void JoinChannel::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

JoinChannel::JoinChannel(const JoinChannel& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:IM.JoinChannel)
}

void JoinChannel::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  user_id_ = GOOGLE_LONGLONG(0);
  channel_id_ = 0;
  result_ = 0;
}

JoinChannel::~JoinChannel() {
  // @@protoc_insertion_point(destructor:IM.JoinChannel)
  SharedDtor();
}

void JoinChannel::SharedDtor() {
  if (this != default_instance_) {
  }
}

void JoinChannel::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* JoinChannel::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return JoinChannel_descriptor_;
}

const JoinChannel& JoinChannel::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_join_5fchannel_2eproto();
  return *default_instance_;
}

JoinChannel* JoinChannel::default_instance_ = NULL;

JoinChannel* JoinChannel::New(::google::protobuf::Arena* arena) const {
  JoinChannel* n = new JoinChannel;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void JoinChannel::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<JoinChannel*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(user_id_, result_);

#undef ZR_HELPER_
#undef ZR_

}

bool JoinChannel::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:IM.JoinChannel)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int64 user_id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &user_id_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_channel_id;
        break;
      }

      // optional int32 channel_id = 2;
      case 2: {
        if (tag == 16) {
         parse_channel_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &channel_id_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_result;
        break;
      }

      // optional int32 result = 3;
      case 3: {
        if (tag == 24) {
         parse_result:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &result_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:IM.JoinChannel)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:IM.JoinChannel)
  return false;
#undef DO_
}

void JoinChannel::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:IM.JoinChannel)
  // optional int64 user_id = 1;
  if (this->user_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->user_id(), output);
  }

  // optional int32 channel_id = 2;
  if (this->channel_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->channel_id(), output);
  }

  // optional int32 result = 3;
  if (this->result() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->result(), output);
  }

  // @@protoc_insertion_point(serialize_end:IM.JoinChannel)
}

::google::protobuf::uint8* JoinChannel::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:IM.JoinChannel)
  // optional int64 user_id = 1;
  if (this->user_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->user_id(), target);
  }

  // optional int32 channel_id = 2;
  if (this->channel_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->channel_id(), target);
  }

  // optional int32 result = 3;
  if (this->result() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->result(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:IM.JoinChannel)
  return target;
}

int JoinChannel::ByteSize() const {
  int total_size = 0;

  // optional int64 user_id = 1;
  if (this->user_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->user_id());
  }

  // optional int32 channel_id = 2;
  if (this->channel_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->channel_id());
  }

  // optional int32 result = 3;
  if (this->result() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->result());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void JoinChannel::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const JoinChannel* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const JoinChannel>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void JoinChannel::MergeFrom(const JoinChannel& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.user_id() != 0) {
    set_user_id(from.user_id());
  }
  if (from.channel_id() != 0) {
    set_channel_id(from.channel_id());
  }
  if (from.result() != 0) {
    set_result(from.result());
  }
}

void JoinChannel::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void JoinChannel::CopyFrom(const JoinChannel& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool JoinChannel::IsInitialized() const {

  return true;
}

void JoinChannel::Swap(JoinChannel* other) {
  if (other == this) return;
  InternalSwap(other);
}
void JoinChannel::InternalSwap(JoinChannel* other) {
  std::swap(user_id_, other->user_id_);
  std::swap(channel_id_, other->channel_id_);
  std::swap(result_, other->result_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata JoinChannel::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = JoinChannel_descriptor_;
  metadata.reflection = JoinChannel_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// JoinChannel

// optional int64 user_id = 1;
void JoinChannel::clear_user_id() {
  user_id_ = GOOGLE_LONGLONG(0);
}
 ::google::protobuf::int64 JoinChannel::user_id() const {
  // @@protoc_insertion_point(field_get:IM.JoinChannel.user_id)
  return user_id_;
}
 void JoinChannel::set_user_id(::google::protobuf::int64 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:IM.JoinChannel.user_id)
}

// optional int32 channel_id = 2;
void JoinChannel::clear_channel_id() {
  channel_id_ = 0;
}
 ::google::protobuf::int32 JoinChannel::channel_id() const {
  // @@protoc_insertion_point(field_get:IM.JoinChannel.channel_id)
  return channel_id_;
}
 void JoinChannel::set_channel_id(::google::protobuf::int32 value) {
  
  channel_id_ = value;
  // @@protoc_insertion_point(field_set:IM.JoinChannel.channel_id)
}

// optional int32 result = 3;
void JoinChannel::clear_result() {
  result_ = 0;
}
 ::google::protobuf::int32 JoinChannel::result() const {
  // @@protoc_insertion_point(field_get:IM.JoinChannel.result)
  return result_;
}
 void JoinChannel::set_result(::google::protobuf::int32 value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:IM.JoinChannel.result)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace IM

// @@protoc_insertion_point(global_scope)
