// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: operate_channel.proto

#ifndef PROTOBUF_operate_5fchannel_2eproto__INCLUDED
#define PROTOBUF_operate_5fchannel_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace IM {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_operate_5fchannel_2eproto();
void protobuf_AssignDesc_operate_5fchannel_2eproto();
void protobuf_ShutdownFile_operate_5fchannel_2eproto();

class OperateChannel;

// ===================================================================

class OperateChannel : public ::google::protobuf::Message {
 public:
  OperateChannel();
  virtual ~OperateChannel();

  OperateChannel(const OperateChannel& from);

  inline OperateChannel& operator=(const OperateChannel& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OperateChannel& default_instance();

  void Swap(OperateChannel* other);

  // implements Message ----------------------------------------------

  inline OperateChannel* New() const { return New(NULL); }

  OperateChannel* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OperateChannel& from);
  void MergeFrom(const OperateChannel& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(OperateChannel* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 user_id = 1;
  void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  ::google::protobuf::int64 user_id() const;
  void set_user_id(::google::protobuf::int64 value);

  // optional int32 channel_id = 2;
  void clear_channel_id();
  static const int kChannelIdFieldNumber = 2;
  ::google::protobuf::int32 channel_id() const;
  void set_channel_id(::google::protobuf::int32 value);

  // optional int32 result = 3;
  void clear_result();
  static const int kResultFieldNumber = 3;
  ::google::protobuf::int32 result() const;
  void set_result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:IM.OperateChannel)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 user_id_;
  ::google::protobuf::int32 channel_id_;
  ::google::protobuf::int32 result_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_operate_5fchannel_2eproto();
  friend void protobuf_AssignDesc_operate_5fchannel_2eproto();
  friend void protobuf_ShutdownFile_operate_5fchannel_2eproto();

  void InitAsDefaultInstance();
  static OperateChannel* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// OperateChannel

// optional int64 user_id = 1;
inline void OperateChannel::clear_user_id() {
  user_id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 OperateChannel::user_id() const {
  // @@protoc_insertion_point(field_get:IM.OperateChannel.user_id)
  return user_id_;
}
inline void OperateChannel::set_user_id(::google::protobuf::int64 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:IM.OperateChannel.user_id)
}

// optional int32 channel_id = 2;
inline void OperateChannel::clear_channel_id() {
  channel_id_ = 0;
}
inline ::google::protobuf::int32 OperateChannel::channel_id() const {
  // @@protoc_insertion_point(field_get:IM.OperateChannel.channel_id)
  return channel_id_;
}
inline void OperateChannel::set_channel_id(::google::protobuf::int32 value) {
  
  channel_id_ = value;
  // @@protoc_insertion_point(field_set:IM.OperateChannel.channel_id)
}

// optional int32 result = 3;
inline void OperateChannel::clear_result() {
  result_ = 0;
}
inline ::google::protobuf::int32 OperateChannel::result() const {
  // @@protoc_insertion_point(field_get:IM.OperateChannel.result)
  return result_;
}
inline void OperateChannel::set_result(::google::protobuf::int32 value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:IM.OperateChannel.result)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace IM

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_operate_5fchannel_2eproto__INCLUDED
